### ISSUE TITLE
error when run "get queries "

### ISSUE THREAD

**Issue by L-Augustine** [EICN-UCLA/cryoID#2]
Hi,
I followed the steps to install the cryoID on CentOS7.  However, when I ran the"Grt queries" , an error occurred. And because I am not good at Linux , the error. was not solved. My phenix could run directly. 
![error](https://github.com/EICN-UCLA/cryoID/assets/75000408/c53679a7-d31f-4cee-a7df-01ef5524e11f)
Can you give me some guidance. Thank you!

Liu

**Comment by PIPAI** [comment]
Hi Liu,

Did you install Phenix already? What if you directly run phenix.sequence_from_map from the terminal line? It seems that either Phenix was not properly installed, or the path was not included in the terminal environment.

Best,

**Comment by L-Augustine** [comment]
Thank you for your reply,
I have already installed Phenix, and I can open it directly from the terminal. 
![sequence_from_map](https://github.com/EICN-UCLA/cryoID/assets/75000408/149f5fe2-4061-4dfc-9f19-1eaf9ae0f4ac)
 
![phenix](https://github.com/EICN-UCLA/cryoID/assets/75000408/d9d412c3-aa34-4a64-af59-c4ced984b119)
![PATH](https://github.com/EICN-UCLA/cryoID/assets/75000408/33799892-123f-41d8-9dda-80bd683ae6a8)
Looking forward to your reply. Thank you!

**Comment by PIPAI** [comment]
Hi Liu,

Phenix seemed properly installed and the version should be good. For the cryoID error, there is supposed an additional line reporting the detailed error occured. Can you paste it here? 
![image](https://github.com/EICN-UCLA/cryoID/assets/7248595/dc1fbbd4-b43a-4121-866c-a5b713515396)

Best,

**Comment by PIPAI** [comment]
By the way, are you running the tutorial data or your own ones?

Best,

**Comment by L-Augustine** [comment]
I ran the tutorial data, and this is the additional line and the log.
[UnkwnPro.log](https://github.com/EICN-UCLA/cryoID/files/13472242/UnkwnPro.log)
![fail](https://github.com/EICN-UCLA/cryoID/assets/75000408/1aa5105f-b90e-4d41-b50a-fc4b0ba0d33b)
Thank you.

**Comment by PIPAI** [comment]
It looked strange...Have you ever succesfully ran any jobs with get_queries?

Alternatively, you may want to directly use phenix.sequence_from_map to generate queries and then use it as inputs for the second step query search.

**Comment by L-Augustine** [comment]
Thank you very much for your help these days!
I directly run the phenix.sequence_from_map and I find that my system killed the process because it was taking up too much memory. I add the memory and it run successfully. 
Sorry to bother you these days and thank you again. Have a nice day.

**Comment by PIPAI** [comment]
Wow it's great to hear that! Finger crossed :)
